ARG BASE_IMAGE_NAME
FROM ${BASE_IMAGE_NAME}

ARG GIT_SHA=00000000
ENV GIT_SHA=${GIT_SHA}

# The `sphinx_rtd_theme` can be removed after the 2.19 release. It's kept for now to ensure compatibility between
# main and 2.19 branches.
RUN pip3 install \
    sphinx==8.1.3 \
    sphinx_rtd_theme==3.0.1 \
    nvidia-sphinx-theme==0.0.9.post1 \
    pydata-sphinx-theme==0.19.0 \
    myst-parser==4.0.1 \
    nbsphinx==0.9.5 \
    IPython \
    ipython_genutils==0.2.0 \
    breathe==4.35.0 \
    ipywidgets==8.0.2 \
    sphinx-autoapi==3.3.2 \
    astroid==3.3.2 \
    sphinx-tabs==3.4.7
RUN apt-get update && apt-get install -y pandoc graphviz doxygen && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/transformerengine
